apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-webapp
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: python-webapp

  template:
    metadata:
      labels:
        app: python-webapp

    spec:
      containers:
        - name: python-webapp

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 5000

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5